Feat/#105
GDSC-PKNU-21-22/pknu-notice-front pull request #106
Opened 2023-07-24 09:04 UTC by hwinkr

## 🤠 개요

* Closes : #105 
* 건의사항을 작성하고 사용자가 보내기 버튼을 누르기 전, 보낸 내용에 대해서 한번더 확인하는 모달을 구현했어요
* 개발이 진행됨에 따라, 모달을 사용하는 컴포넌트가 많아져서 각 컴포넌트가 모달의 상태를 가지고 있는게 비효율적이라고 판단했고 따라서 모달의 상태를 전역으로 빼기로 결정했어요

## 💫 설명

* 전역으로 관리 할 모달의 상태
  * boolean값을 사용해서 모달의 상태를 관리하려고 했으나, 이 방법을 사용하면 한 모달이 렌더링 되면 모든 모달이 렌더링 되는 문제가 발생해요
  * 전역으로 관리 하는 모달의 상태는 객체 배열이에요.
  ```typescript
   const 모달전역상태 = [
    {
      Component: // something....
      props: // something...
    },
    {
      //...
    }
  ]
  ```
  * modals - 객체 배열 / setModals: 객체 배열을 수정할 수 있는 함수

* 모달의 표준화
  * 앱 내부에서 사용하는 모달을 표준화 했어요
  * 크게 보면 경고, 확인, 건의사항전송 모달이 필요해서 이 3개의 컴포넌트에 필요한 메세지를 주입할 수 있도록 추상화 했어요
 
* useModals 훅
  * 코드 
  ```typescript
  const useModals = () => {
      //...
      const openModal = useCallback(
      <T extends FunctionComponent<any>>(
        Component: T,
        props: Omit<ComponentProps<T>, 'open'>,
      ) => {
        setModals((modals) => [
          ...modals,
          { Component, props: { ...props, open: true } },
        ]);
      },
      [setModals],
    );
  
    const closeModal = useCallback(
      <T extends FunctionComponent<any>>(Component: T) => {
        setModals((modals) =>
          modals.filter((modal) => modal.Component !== Component),
        );
      },
      [setModals],
    );
    return {
      modals,
      openModal,
      closeModal,
    };
  };
  ```
  * 사용방법 : 모달을 열고 닫아야할 상황에 따라 `openModal`, `closeModal`을 호출해요
  ```typescript
  const handleMajorModal = () => {
    if (major) {
      routerToPath(path);
      return;
    }
    openModal(AlertModal, {
      message: MODAL_MESSAGE.ALERT.setMajor,
      buttonMessage: '전공선택하러 가기',
      iconKind: 'plus',
      onClose: () => closeModal(AlertModal),
      routerTo: () => {
        closeModal(AlertModal);
        routerToMajorDecision();
      },
    });
  };
  ```
* 변경된 테스트 코드
  * 커스텀 훅인 `useModals`를 호출하고 상황에 따라서, `openModals` 함수가 예상되는 인자와 함께 호출 되는지를 테스트 했어요

## 📷 스크린샷 (Optional)

https://github.com/hwinkr/algorithm/assets/68489467/4eb44e8b-4eb4-4686-9d0b-12d0c876e232

https://github.com/hwinkr/algorithm/assets/68489467/00e89e68-4575-4603-9c5e-5fc1eba1b6cc

2023-07-25 06:03 UTC, pp449 requested changes
제가 얕아서 코드 이해하는데 조금 오래 걸렸네요.. ㅎㅎㅎ 
useModals 파일 커밋이 뒤에 있어서 이전 커밋에 useModals를 사용하는 컴포넌트를 보기 힘들었던거 같아요!

전역 상태관리로 어떻게 모달을 관리할 수 있을지 생각했는데

전역상태로 모달을 가지고 pages 또는 component 에서 모달을 보여주는게 아니라 아래 컴포넌트를 통해 모달창을 보여주는 방식이 신선했어요!  되게 아이디어가 좋은거 같아요
``` tsx
import useModals from '@hooks/useModals';
import React from 'react';

const Modals = () => {
  const { modals } = useModals();

  return (
    <>
      {modals.map(({ Component, props }, idx) => {
        return <Component key={idx} {...props} />;
      })}
    </>
  );
};

export default Modals;
```

2023-07-25 08:35 UTC, hwinkr commented on src/components/Modal/AlertModal/index.tsx
> +              {iconKind && <Icon kind="plus" color={THEME.TEXT.WHITE} />}
실수했네요,,ㅎ 수정 할게여

2023-07-25 08:35 UTC, hwinkr commented on src/constants/modal-messages.ts
> +    postSuggestion: '건의사항을 보내시겠어요?',
upper, lower 둘 중에 고민 했는데 다 upper로 수정 할게요~

2023-07-25 08:35 UTC, hwinkr commented on src/components/List/DepartmentList/index.test.tsx
> +        ,
ㅋㅋㅋㅋㅋ..ㅎ

2023-07-25 08:37 UTC, hwinkr commented on src/hooks/useModals.ts
> +      ]);
* 건의사항 작성 모달
* 건의사항 내용 확인 모달
이 경우에는 2가지 모달이 둘 다 렌더링 돼야 해서 map을 사용했어요!

2023-07-25 08:49 UTC, pp449 commented on src/hooks/useModals.ts
> +      ]);
아 건의사항 작성하는 모달은 
모달 위해 모달이 하나 더 올라가는 경우가 있네요! 이 부분은 생각 못했네요 👍

2023-07-25 09:22 UTC, hwinkr commented on src/hooks/useModals.ts
> +  const openModal = useCallback(
openModal, closeModal은 Context API를 통해서 관리되는 전역 상태가 아닌, 전역으로 관리되는 모달의 렌더링 상태(Component, props)를 제어할 수 있는 함수 입니다.
자바스크립트의 함수는 오직 자신에게만 동등하고, 리렌더링이 되기 전과 후의 함수도 다릅니다.
같은 기능을 하는 함수 객체가 계속해서 재생성되는 것을 막기 위해서 useCallback을 사용했는데요, 예상 가능한 시나리오는 다음과 같습니다.

> 어떤 컴포넌트에서 openModal 호출로 모달을 렌더링 -> 상태를 변경하는 setModal이 호출되기 때문에 리렌더링이 발생 -> openModal은 useCallback 훅이 반환해주는 함수를 사용하고, **상태를 변경하는 setModal 함수는 변경되지 않았기 때문에 캐쉬된 함수를 다시 받음**

이 시나리오를 통해서 동일한 기능을 하는 함수가 계속해서 재생성 되는것을 조금이나마 막을 수 있음을 예상해볼 수 있습니다.

2023-07-25 14:10 UTC, pp449 approved these changes
이번 모달창으로 많이 배워갑니다~

2023-07-25 14:10 UTC, merged

2023-07-27 08:21 UTC, hwinkr commented on src/hooks/useModals.ts
> +  const openModal = useCallback(
저번 답변에 확신이 없어서, 오늘 실험을 해봤는데 성능 개선에 도움이 안되는 것 같아요.
useCallback훅으로 감싼건 수정하도록 할게요