Fix: 학부/학과와 전공 모두 있는경우 전공만 저장하도록 수정
GDSC-PKNU-21-22/pknu-notice-front pull request #110
Opened 2023-07-26 05:45 UTC by pp449

## 🤠 개요

- closes: #109 
- 학부/학과와 전공 모두 있는경우 전공만 저장하도록 수정했어요
- 테스트코드의 경우 모달창에 확인을 누른경우 함수가 실행되어야는데 모달(useModals)을 모킹했기 때문에 테스트가 안되어 skip으로 바꿨어요!

## 💫 설명

## 📷 스크린샷 (Optional)

2023-07-26 10:00 UTC, hwinkr requested changes
✅ LGTM

2023-07-26 10:51 UTC, pp449 commented on src/components/List/DepartmentList/index.test.tsx
> +  it.skip('학과 이름에 스페이스가 있는 경우 (학부, 전공이 모두 있는경우) 테스트', async () => {
이 테스트는 학과 이름이 '조형학부 건축학전공' 인 경우 '건축학전공' 으로 선택되는지 확인하는 테스트라서 테스트 명제랑 내용이 맞지 않는거 같아요!

2023-07-31 01:32 UTC, hwinkr approved these changes
흠...계속 통과하도록 수정해보고 있는데 잘 안되네여..일단 skip 합시다

2023-07-31 01:55 UTC, hwinkr commented
merge 부탁드려요~

2023-07-31 03:53 UTC, merged