Style/#114: Header, Footer 크기 변경
GDSC-PKNU-21-22/pknu-notice-front pull request #115
Opened 2023-07-31 06:51 UTC by pp449

## 🤠 개요

- closes: #114 
- position fixed 로 변경하고 콘텐츠가 헤더와 푸터로 비치지 않도록 만들었어요!

## 💫 설명

## 📷 스크린샷 (Optional)

2023-07-31 14:17 UTC, hwinkr requested changes
✅

2023-07-31 14:17 UTC, hwinkr commented on src/components/Header/index.tsx
> +  background-color: white;
같은 white 이긴 하지만 미리 설정해둔 상수를 사용하면 더 괜찮을 것 같네요! 
footerTab에도 있어요~!

2023-07-31 14:17 UTC, hwinkr commented on src/components/Header/index.tsx
> +  height: 8%;
저 지도 페이지 구현할 때, header & footerTab모두 높이를 5vh, 패딩을 10px로 동일하게 설정하고 지도 페이지에서 `calc(90vh - 40px)`를 통해서 딱 가운데에 오도록 설정 했었는데 8%로 변경 해서 계산이 안맞을거 같아서 조금 걱정 되네요..의논 해봐야할 것 같아요!

2023-08-01 10:36 UTC, pp449 commented on src/components/Header/index.tsx
> +  background-color: white;
수정했어요~

2023-08-01 11:08 UTC, hwinkr approved these changes
✅ good

2023-08-01 11:13 UTC, merged