Feat/#246: 사이드바 구현 & 부림이 앱 아이콘 백경이 버젼 추가
GDSC-PKNU-21-22/pknu-notice-front pull request #257
Opened 2023-10-01 03:45 UTC by hwinkr

## 🤠 개요

- closes : #246 
- 사이드바를 구현 했어요

## 💫 설명

- 부림이 앱 내부에서 사용할 사이드바를 구현했어요
  - 슬라이드 애니메이션을 적용해서 마운트, 언마운트가 최대한 부드럽게 진행될 수 있도록 했어요
- 백경이 이미지를 앱 아이콘으로 사용하기 위해서 사이즈별로 이미지를 업로드 해뒀어요

## 📷 스크린샷 (Optional)

https://github.com/GDSC-PKNU-21-22/pknu-notice-front/assets/68489467/eae0c8e8-91e8-4b6a-963b-5e0255fc37fd

2023-10-01 04:05 UTC, pp449 approved these changes
interface 에 readonly 도 있던걸 까먹고 있었네요. 저도 자주 사용해야겠어요
사이드바가 부드럽게 잘 동작하네요! border-bottom 색상이 너무 진한거 같은데 전공 선택에 사용되는 색상이랑 동일하게 하는건 어떨까요

2023-10-02 01:58 UTC, pp449 requested changes
지금 manifest.json 의 아이콘 설정이랑 push 알림올때 사용되는 아이콘을
public/icons 로 설정해뒀는데

icons-백경 -> icons 로 이름을 변경하고
기존 부림이 아이콘을 icons -> tmp_icons 와 같이 변경하는건 어떨까요?

2023-10-02 11:47 UTC, hwinkr commented
의견 반영 완료 했어요~

2023-10-02 12:45 UTC, pp449 approved these changes
✅GOOD 좋아요!

2023-10-03 07:41 UTC, merged