Feat/#54: 단과대 선택 페이지 추가
GDSC-PKNU-21-22/pknu-notice-front pull request #69
Opened 2023-05-10 11:48 UTC by pp449

## 🤠 개요
- Closes: #54 
- 단과대 선택 페이지랑 학과 선택 페이지는 따로 이슈를 만들어서 개발할게요
- 단과대 선택 시 URL 이동까지 구현했어요

## 💫 설명
- 단과대 선택 페이지랑 학과 선택 페이지를 같이 올리면 커밋이랑 변경내용이 너무 많을거 같아서 따로 올릴게유,,
- URL 에 한글을 넣을 수 없기에 encoding 된 값을 올렸어요

## 📷 스크린샷 (Optional)
![image](https://github.com/GDSC-PKNU-21-22/pknu-notice-front/assets/71641127/6149da1a-a755-4bfa-9b56-fde5c1f6f0ef)
<img width="1840" alt="image" src="https://github.com/GDSC-PKNU-21-22/pknu-notice-front/assets/71641127/20fdec49-fc46-4c13-a5b7-caef8a9ef9f8">

2023-05-12 09:51 UTC, hwinkr requested changes
👍 이번 이슈는 좀 구현이 빡세보이네요..생각할것 도 많을 것 같아요~ 화이팅!

2023-05-12 09:51 UTC, hwinkr commented on src/App.tsx
> +      <Route path="/major-decision" element={<CollegeList />} />
`ColllegeList` 컴포넌트는 `components` 폴더로 이동하는 것이 더 좋을것 같아요~
`/major-decision` 경로로 이동하면,  `MajorDecision` 컴포넌트 내부에서 `CollegeList` 를 호출해서 사용할 것 같은데 `CollegeList` 는 페이지의 구성요소 느낌에 더 가까우니까 components 폴더로 이동해서
* CollegeList
  * 단과대 컴포넌트
    * index.tsx
    * index.test.tsx
  * 학과 컴포넌트
    * index.tsx
    * index.test.tsx

이렇게 분리하는것이 더 괜찮을 것 같아요~

2023-05-12 09:51 UTC, hwinkr commented on src/mocks/handlers/majorHandlers.ts
> +  rest.get(MOCKSERVERURL + '/majorDecision/:college', (req, res, ctx) => {
혹시, 경로 파라미터에서 쿼리 파라미터로 사용해보면 인코딩을 안해도 되려나요?
```typescript
// announceHandlers.ts
rest.get(`${SERVER_URL}/announcement`, (req, res, ctx) => {
    const query = req.url.searchParams;
    if (query.get('major') === '컴퓨터공학과') {
//...
```
확실하지는 않지만, 제 모킹 데이터 핸들러 함수 코드에서 저는 쿼리 파라미터를 사용해서 그런지 인코딩과 관련된 에러가 발생하지 않았었어요~ 한번 쿼리 파라미터로 변경해서 시도해보면 좋을 것 같습니다!

2023-05-13 07:08 UTC, pp449 commented on src/mocks/handlers/majorHandlers.ts
> +  rest.get(MOCKSERVERURL + '/majorDecision/:college', (req, res, ctx) => {
여기서 말하는 인코딩은 한글을 URL 에 적용하기 위해 ASCII 로 바꾸는 인코딩인가요??

인코딩 관련 에러가 어떤 에러인지 잘 모르겠어요.. 😢

2023-05-17 14:21 UTC, dohun31 reviewed
정말 잘하고 계시네요!!!!!!

2023-05-17 14:21 UTC, dohun31 commented on src/components/List/CollegeList/index.tsx
> +      const ENCODECOLLEGENAME = encodeURI(encodeURIComponent(COLLEGENAME));
얘네들이 상수일까요? 이 부분에 대해서 컨벤션을 따로 정해뒀으면 괜찮지만 아니라면 네이밍이 상수처럼 되어있어서 헷갈릴 수 있을것 같네요

2023-05-17 14:21 UTC, dohun31 commented on src/components/List/CollegeList/index.tsx
> +  const onClick = (e: React.MouseEvent<HTMLElement>) => {
```tsx
const onClick: React.MouseEventHandler<HTMLElement> = (e) => {}
```
함수표현식은 이렇게 함수 자체의 타입을 지정해줄 수 있어요~

2023-05-17 14:21 UTC, dohun31 commented on src/App.tsx
> +      <Route path="/major-decision" element={<CollegeList />} />
저는 pages는 정말 말 그대로 페이지 단위로 사용해요.

```tsx
function Home() {
  return (
    <>
      <Header />
      <Main>
        <CollegeList />
        ...
      </Main>
      <Footer />
    </>
  )
}
```

2023-05-17 14:21 UTC, dohun31 commented on src/components/List/CollegeList/index.tsx
> +      const COLLEGENAME = e.currentTarget.textContent as string;
textContent의 타입이 `"string" | null`인걸로 알고 있는데 이런 경우엔 타입 단언보단 early return해버려도 좋을 것 같아요

타입 단언은 생각보다 위험할 수 있어요!

2023-05-17 14:21 UTC, dohun31 commented on src/components/List/CollegeList/index.tsx
> +    if (e.target === e.currentTarget) {
이 부분도 아래와 비슷한 의견인데 `e.target === e.currentTarget`인 경우만 살아남아야 한다면 early return해서 depth가 깊어지지 않게 해주면 좋을것 같아요

나중에 조건이 추가되면 함수의 depth가 깊어져서 유지보수하기 힘들어지고 한눈에 맥락을 파악하기 어려워집니다.
```tsx
// early return ❌
if(e.target === e.currentTarget) {
  if(condition1) {
    ...
  } else {
    ...
  }
}

// early return ✅
if(e.target !== e.currentTarget) return;

if(condition) {
  ...
} else {
 ...
}

2023-05-17 14:21 UTC, dohun31 reviewed
정말 잘하고 계시네요!!!!!!

2023-05-20 01:49 UTC, pp449 commented on src/components/List/CollegeList/index.tsx
> +      const ENCODECOLLEGENAME = encodeURI(encodeURIComponent(COLLEGENAME));
일반 상수도 UPPERCASE 인줄 알았어요 요 부분도 수정해야겠군요

2023-05-20 01:51 UTC, pp449 commented on src/components/List/CollegeList/index.tsx
> +  const onClick = (e: React.MouseEvent<HTMLElement>) => {
아 함수 자체에도 타입을 넣을수 있군요 ㅎㅎ 
해당 코드가 더 좋아보여요

2023-05-20 01:53 UTC, pp449 commented on src/components/List/CollegeList/index.tsx
> +      const COLLEGENAME = e.currentTarget.textContent as string;
early return 을 하면 'as string' 으로도 굳이 타입을 설정 안해도 될거 같군요
반영해서 수정할게요 ㅎㅎ

2023-05-20 02:03 UTC, pp449 commented on src/components/List/CollegeList/index.tsx
> +    if (e.target === e.currentTarget) {
넵 반영할게요
시간될때마다 자주 놀러와요 ~

2023-05-20 05:35 UTC, pp449 commented
수정완료 ~

2023-05-20 05:47 UTC, pp449 commented
마이크 체크~

2023-05-21 02:06 UTC, hwinkr approved these changes
✅LGTM

2023-05-21 02:27 UTC, merged