Test/#68: msw 사용해서 공지사항 컴포넌트 테스트 로직 수정
GDSC-PKNU-21-22/pknu-notice-front pull request #71
Opened 2023-05-10 14:27 UTC by hwinkr

## 🤠 개요

* Closes: #68 
* msw 를 사용해서 모킹 데이터를 받아 실제 서버가 있는 환경에서 동작하는 것 처럼 구현 후, 테스트 로직을 수정 했어요.

## 💫 설명

* msw 에서는 서버 url 경로와 쿼리 파라미터를 분리해야 해요
  * 쿼리 파라미터를 사용한 서버 uri 는 일반적으로 RESTful API 의 규칙에는 맞지 않는다고 하네요, 따라서 테스트 환경에서 uri 에 쿼리 파라미터를 포함하면 에러를 뱉어요
  * `rest.get` 함수의 RESTful API 의 규칙에 맞게 첫번째 인자에 서버 url 주소나 경로 파라미터(/:userId) 를 사용해야 해요
  * 이후 핸들러 내부에서 쿼리 파라미터를 가져와서 해당 쿼리 파라미터를 이용한 응답 데이터를 반환하도록 해야 해요
```typescript
export const announceHandlers: RequestHandler[] = [
  rest.get(`${SERVER_URL}/announcement`, (req, res, ctx) => {
    const query = req.url.searchParams;
    if (query.get('major') === '컴퓨터공학과') {
```

* desc 는 크롤링할 데이터마다 내용이 천차만별이라서 삭제하기로 했어요

* SSR 환경에서는 스타일 요소도 같이 SSR 되기 때문에 `nth-child` 선택자는 보안적으로 안전하지 않을 수 있다고 합니다, 따라서 `nth-of-type` 으로 변경했어요,

## 📷 스크린샷 (Optional)

<img width="614" alt="Screenshot 2023-05-10 at 22 50 13" src="https://github.com/hwinkr/algorithm/assets/68489467/82eecfb6-c76d-42d6-b2c8-4acb17eb8a81">

2023-05-12 07:47 UTC, pp449 requested changes
API 통신방법을 모듈화된 http 로 통일하는건 어떤가용

2023-05-12 07:47 UTC, pp449 commented on src/apis/announcement.ts
> +};
여기서 fetch를 이용한 통신보다 /apis/http 의 모듈을 이용하여 getAnnounceList() 함수를 AnnounceList 컴포넌트 내부 함수로 넣어서 사용하는건 어떤가요??

그러면 서버 URL 도 따로 가져올 필요없이 const fetchResult = http.get(`/announcement?major=${major}`);
와 같이 사용할 수 있고, fetch와 axios 혼용해서 쓰는거 보다 하나로 통일하는게 좋을거 같아요!

https://www.notion.so/Fetch-vs-Axios-8640c5ff04d942d2bee2e4049084a8df?pvs=4
내용과 같이 만약 추후에 AnnounceList 컴포넌트를 테스트하면 jest 에서 에러가 나요

2023-05-12 07:47 UTC, pp449 commented on src/components/Card/AnnounceCard/index.test.tsx
> +    );
여기에도 모듈화되어있는 apis/http 를 사용하는게 좋을거 같아요

2023-05-12 09:23 UTC, hwinkr commented on src/apis/announcement.ts
> +};
아 저희 api 요청도 모듈화 했었던걸 잠시 잊었습니다..ㅎ.ㅎ
수정 할게요~

2023-05-13 07:11 UTC, pp449 approved these changes
조아요 ~~

2023-05-14 12:56 UTC, merged