Feat/#70: 학과 선택페이지 구현
GDSC-PKNU-21-22/pknu-notice-front pull request #79
Opened 2023-05-22 14:00 UTC by pp449

## 🤠 개요
- Closes: #70 
- 수정한게 좀 많아요..
- 일단 PR 올리고 조금씩 수정해갈게요 !

## 💫 설명
### 변경사항
원래있던 단과대 선택 컴포넌트를 재사용할 수 있도록 수정해서 사용했어요

### 현재 기능 외 수정사항
#### @components/Button/index.ts
onClick 이벤트의 다양한 타입을 받을 수 있도록 타입을 변경했어요
```
onClick?: any;
```

#### majorContext (전역 Context) 
현재 major 타입이 '컴퓨터공학과' 로 한정되어 있어서 string 타입으로 변경했어요

### 문제사항
URL 변경 테스트가 제대로 동작하지 않음을 알아냈어요 ! 그래서 일단 URL 변경 테스트에 관련한 코드는 모두 skip 처리 해뒀어요 

## 📷 스크린샷 (Optional)

https://github.com/GDSC-PKNU-21-22/pknu-notice-front/assets/71641127/4c2c1e60-c9d5-491b-81dd-ac013c47bd6b

2023-05-23 02:40 UTC, dohun31 commented
> @components/Button/index.ts
> onClick 이벤트의 다양한 타입을 받을 수 있도록 타입을 변경했어요
>
> onClick?: any;

혹시 다양한 타입에 대한 예시가 있을까요?
onClick 이벤트가 function 타입 말고 어떤게 올 수 있나요?

2023-05-23 08:21 UTC, pp449 commented
> > @components/Button/index.ts
> > onClick 이벤트의 다양한 타입을 받을 수 있도록 타입을 변경했어요
> > onClick?: any;
> 
> 혹시 다양한 타입에 대한 예시가 있을까요? onClick 이벤트가 function 타입 말고 어떤게 올 수 있나요?

function 타입인데 매개변수가 어떤 타입이든 올 수 있을거 같아서 any로 지정했는데 혹시 더 좋은방법이 있을까요??

2023-05-23 08:48 UTC, dohun31 commented
> function 타입인데 매개변수가 어떤 타입이든 올 수 있을거 같아서 any로 지정했는데 혹시 더 좋은방법이 있을까요??

<br />


function 타입이라는건 동일하고 매개변수 타입이 예측 불가능한거라면 제너릭 타입을 사용하면 좋을 것 같네요~ 
 
그런데 onClick이벤트는 button 컴포넌트에서 컨트롤하는데 어떻게 매개변수가 달라지나요??
가령 아래와 같은 버튼을 사용한다고 하더라도
```tsx
// case 1
<Button onClick={(some: number) => {
  //  doSomeThing
}} />


// case 2
<Button onClick={(some: string) => {
  //  doSomeThing
}} />
```

버튼에서 이미 `onClick:  MouseEventHandler`로 타입이 정해지고, 매개변수는 `e: MouseEvent`만 올 수 있을 것 같은데 매개변수를 다르게 하는게 의미가 있나요?
```tsx
const Button = ({ children, disabled = false, ...props }: ButtonProps) => {
  return (
    <StyledButton type="button" disabled={disabled} {...props}> // 여기서 onClick 등록됨
      {children}
    </StyledButton>
  );
};
```

정리하면 매개변수의 관리 주체?는 Button을 소비하는 쪽이 아니라 선언한 쪽입니다!
아무리 onClick 매개변수를 다르게 주더라도 결국 Button에선 e만 전달하고 있어요

2023-05-23 09:59 UTC, dohun31 commented
> 제 생각이 짧았군요,, onClick 에 e:MouseEvent 외에도 다른 매개변수를 쓸 수도 있겠다 싶었는데 그게 아니었네요,, 생각없이 any type 을 붙인거 같아요 바로 수정할게요 !

매개변수 다르게 사용하고 싶으면 이런식으로 하면 될 것 같아요!
중요한건 어떤 매개변수를 전달할지는 Button에서 정하는거!!!

```tsx
interface ButtonProps {
  onClick: (value: string) => void;
}

const Button = ({ children, disabled = false, onClick, ...props }: ButtonProps) => {
  return (
    <StyledButton type="button" disabled={disabled} onClick={(e) => { onClick(e.target.value) }} {...props}> // 여기서 onClick 등록됨
      {children}
    </StyledButton>
  );
};

2023-05-23 10:10 UTC, pp449 commented
> 매개변수 다르게 사용하고 싶으면 이런식으로 하면 될 것 같아요! 중요한건 어떤 매개변수를 전달할지는 Button에서 정하는거!!!
> 
> ```tsx
> interface ButtonProps {
>   onClick: (value: string) => void;
> }
> 
이렇게 보니까 코드가 더욱 복잡한 느낌이.. ㅋㅋㅋㅋㅋㅋ
MouseEventHandler 타입이 좋은거 같아요 !

시간되면 학과선택 컴포넌트는 어떤지 리뷰 가능할까요? 사실 폴더명을 List로 한게 안어울리는것 같기도 하고 
재사용할 수 있도록 코드 작성하느라 코드가 보기 힘들어진거 같아요,,

2023-05-23 12:44 UTC, dohun31 commented
복잡성은 경우 마다 다를 것 같아요~ 
```tsx
// case 1
const onClick = (value: string) => {
  // value를 바로 사용할 수 있다.
}

// case 2
const onClick = (e: MouseEvent<HTMLButtonElement>) => {
  // e를 직접 다뤄야 한다.
}
```

`case 1`의 경우 value만 신경쓰면 돼요. -> 관심사를 분리할 수 있다.
예를 들어 `Input`같은 경우 `value`를 받아서 바로 처리할 수 있어요.

`case 2`의 경우 사용자의 선택지가 더 넓어지지만 e를 직접 다뤄야하고, e.target으로 직접 dom을 제어한다던지 오히려 관심사가 섞이는 경우가 발생할 수 있어요.

캡슐화한다고 생각하면 될 것 같아요~ private처럼 외부에 보여줄 것만 보여줄 수 있게 조금의 제한을 두는 느낌?

2023-05-23 13:00 UTC, dohun31 commented
@pp449 코드 흐름을 한번만 설명해주세요!!
`CollegeList`랑 `DepartmentList`, `List`의 흐름!

2023-05-24 05:14 UTC, pp449 commented
CollegeList 는 단과대 선택하는 컴포넌트
DepartmentList 는 학과를 선택하는 컴포넌트에요
이 두 개의 컴포넌트가 비슷하다보니 List 를 이용해서 중복되는 코드를 줄여줬어요!

먼저 CollegeList ('/majorDecision') 에 접속하면 단과대이름을 fetch 해오고 List 컴포넌트로 단과대 이름을 보여주고 클릭하면 바로 ('/majorDecision?major=정융대') 이런 식으로 라우팅을 시켜요

그리고 CollegeList('/majorDecision?major=정융대') 에 접속하면 <DepartmentList /> 컴포넌트를 렌더링하게 했어요

DepartmentList 컴포넌트는 props 로 받은 단과대 정보를 이용해 학과이름을 fetch 해오고 List 컴포넌트로 학과 이름을 보여줘요
여기서 학과이름을 클릭하면 클릭된 학과의 아이콘이 변경돼요 !

2023-05-24 05:20 UTC, pp449 commented
List 컴포넌트의 경우 props 로 받은 값들을 리스트형태로 보여주는데 아래 코드를 어떻게 수정하면 좋을지 모르겠어요

``` tsx
const [selected, setSelected] = useState<string | null>();

  const onClick: React.MouseEventHandler<HTMLElement> = (e) => {
    if (e.target !== e.currentTarget) return;
    setSelected(e.currentTarget.textContent);
    props.onClick(e);
  };
  ```
``` tsx
        <ListWrapper key={content} onClick={onClick}>
          {content}
          <IconWrapper>
            <Icon
              kind={selected === content ? props.altIcon : props.icon}
              color={selected === content ? THEME.PRIMARY : THEME.TEXT.GRAY}
            />
          </IconWrapper>
        </ListWrapper>
```

학과 선택창에서 선택된 학과는 다른 아이콘(체크된 아이콘)을 보여주기 위해 만약 리스트를 클릭하면 selected 라는 state 를 변경시키고 선택된 리스트는 props로 받은 altIcon 을 보여주게 했어요

그리고 props 로 받은 onClick 이벤트도 처리하기 위해 아래와 같이 onClick 이벤트에 props 로 받은 onClick 이벤트도 실행하도록 했어요

2023-05-27 09:35 UTC, hwinkr requested changes
✅ 학과 페이지 구현 빡세네요..

2023-05-27 09:35 UTC, hwinkr commented on src/App.tsx
>        <Route path="/announcement" element={<Announcement />} />
```typescript
const App = () => {
  return (
    <Routes>
      <Route path="/" element={<Home />} />
      <Route path="/announcement" element={<Announcement />} />
      <Route path="/my" element={<My />} />
      <Route path="/major-decision/*" element={<MajorDecision />} />
    </Routes>
  );
};
```
App 컴포넌트를 위와 같이 수정하고,
```typescript
const MajorDecision = () => {
  return (
    <Routes>
      <Route path="/" element={<CollegeList />} />
      <Route path="/:college" element={<DepartmentList />} />
    </Routes>
  );
};
```
이렇게 경로 파라미터를 통해서 경로를 기준으로 렌더링 할 컴포넌트를 나누는게 더 괜찮은 것 같아요!

2023-05-27 09:35 UTC, hwinkr commented on src/components/List/CollegeList/index.tsx
> +    />
`CollegeList`, `DepartmentList` 모두 **학부/학과 선택하기** 로 같은 title 을 사용하고 있는 것 같은데 이렇게 하기 보다 
`CollegeList` 에서는 **학부 선택하기**
`DepartmentList` 에서는 **학과 선택하기**
이렇게 좀 더 디테일 하게 props 를 넘겨주는게 더 괜찮을 것 같아요!

2023-05-27 09:35 UTC, hwinkr commented on src/components/List/CollegeList/index.tsx
>      else routerTo(`/major-decision?major=${collegeName}`);
`if`, `else` 로 분기를 나눈 이유가 있나요??
```typescript
const onClick: React.MouseEventHandler<HTMLElement> = (e) => {
    if (e.target !== e.currentTarget) return;
    routerTo(`/major-decision?major=${e.currentTarget.textContent}`);
  };
```
이렇게 사용해도 괜찮을 것 같아요!

2023-05-27 09:35 UTC, hwinkr commented on src/components/List/index.tsx
> +const List = (props: ListProps) => {
`CollegeList`, `Department` 2개의 컴포넌트에서만 `List` 컴포넌트를 호출하는데 각 컴포넌트에서 필요로 하는 로직이 많이 상이한 것 같습니다..!
* CollegeList
  * 단과대 버튼을 클릭하면 바로 페이지 이동을 한다.
  * `check`, `uncheck` 의 상태에 따른 `icon` 의 변화가 필요하지 않다.
* DepartmentList
  * 학부 버튼을 클릭하면 전역상태를 설정할 수 있다.
  * `check`, `uncheck` 의 상태에 따른 `icon` 의 변화가 필요하다.
  * 페이지 이동이 필요가 없다.

이렇게 정리해볼 수 있을 것 같은데 필요한 로직이 달라서 `List` 컴포넌트 내부 로직이 많이 복잡해 보이는 것 같습니다.
`List` 컴포넌트가 2개의 컴포넌트에서만 재사용한다면 `List` 컴포넌트를 따로 빼지 않고 구현하는 것도 괜찮을 것 같네요!

2023-05-27 09:35 UTC, hwinkr requested changes
✅ 학과 페이지 구현 빡세네요..

2023-05-27 11:16 UTC, pp449 reviewed
확실히 쿼리 파라미터보단 경로 파라미터가 좋을거 같네용

2023-05-27 11:16 UTC, pp449 commented on src/components/List/CollegeList/index.tsx
>      else routerTo(`/major-decision?major=${collegeName}`);
잘못된 query 값을 가지고 요청하는 경우에는 블락하기 위해 사용했어요! 예를들어 사용자가 직접 url 에 '/major-decision?major=부산대' 로 입력한 경우를 막기 위해서 적었어요
URL 파라미터를 사용한다면 MajorDecision 컴포넌트에서 해당 문제를 처리할게요!

2023-05-27 11:16 UTC, pp449 commented on src/App.tsx
>        <Route path="/announcement" element={<Announcement />} />
그렇다면 아래와 같이 작성하는게 더 보기 편하지 않을까요??
```
<Routes>
      <Route path="/" element={<Home />} />
      <Route path="/announcement" element={<Announcement />} />
      <Route path="/my" element={<My />} />
      <Route path="/major-decision" element={<CollegeList />} />
      <Route path="/major-decision/:college" element={<DepartmentList />} />
 </Routes>
    ```

2023-05-27 11:16 UTC, pp449 commented on src/components/List/CollegeList/index.tsx
> +    />
그게 더 명시적이고 좋을거 같네요 바로 수정하겠습니다~

2023-05-27 11:16 UTC, pp449 commented on src/components/List/index.tsx
> +const List = (props: ListProps) => {
그래서 이 부분이 고민 많았어요.. 어떻게보면 다른 로직이지만 또 어떻게 보면 동일한 CSS 를 사용하다보니 '중복된 코드를 줄이는게 좋지 않을까?' 생각해서 `List` 컴포넌트를 만들어서 호출했는데 코드가 많이 복잡해보이더라고여..
이 부분은 한번 얘기를 나눠보는게 좋을거 같아요!

2023-05-29 15:18 UTC, hwinkr commented on src/App.tsx
>        <Route path="/announcement" element={<Announcement />} />
음..그 방법도 괜찮을 것 같지만, 제가 생각했을 때는 
```typescript
<Routes>
  <Route path="/" element={<Home />} />
  <Route path="/announcement" element={<Announcement />} />
  <Route path="/my" element={<My />} />
  <Route path="/major-decision" element={<MajorDecision />} />
</Routes>
```
`major-decision` 경로에서 `<MajorDecision />` 컴포넌트를 렌더링 하고 이 컴포넌트 내부에서 다시 라우팅을 분리 해주는 방법도  괜찮다는 생각이 드는데, App 컴포넌트에서는 큰 경로들만 나누어서 라우팅을 정해주고 세부적인 경로들은 페이지 컴포넌트 내부에서 해주는게 컴포넌트 관심사 분리 해주는 것과 비슷해서 뭔가 더 깔끔한 것 같다는 생각을 했었습니다~
저희는 페이지가 그렇게 많지 않을것 같아서 App 에서 다 분리 해줘도 괜찮을 것 같아요~

2023-05-30 06:24 UTC, pp449 commented on src/App.tsx
>        <Route path="/announcement" element={<Announcement />} />
다시 생각해보니 이 방법이 더욱 보기 편할거 같네요 이대로 수정하겠습니닷

2023-05-30 06:24 UTC, pp449 commented
수정완료~

클릭시 애니메이션을 넣으려 했는데 나중에 서스팬스로 구현하는게 더 이쁠거 같아서 일단 애니메이션 추가는 남겨뒀어요~

2023-06-02 05:40 UTC, pp449 commented
테스트코드까지 수정완료 !

2023-06-02 12:18 UTC, hwinkr approved these changes
✅ LGTM!

2023-06-02 15:01 UTC, merged